name: My Artifact Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create artifact file
        run: |
          mkdir -p output
          echo "This is a test artifact file." > output/test.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-artifact
          path: output/test.txt

  process:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: test-artifact

      - name: Show artifact contents
        run: cat test.txt
