name: Process hi.txt Workflow
on:
  push:
    branches:
      - main  # Укажите ветку, в которую будет происходить push
      # - other-branch  # Вы можете добавить другие ветки, если нужно

jobs:
  create_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create a text file
        run: |
          echo "This is the content of hi.txt" > hi.txt
          echo "Файл hi.txt создан."

      - name: Upload 12.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: text-file-artifact
          path: hi.txt

  process_file:
    runs-on: ubuntu-latest
    needs: create_file
    steps:
      - name: Download text file artifact
        uses: actions/download-artifact@v4
        with:
          name: text-file-artifact

      - name: Read and display the content of 12.txt
        run: |
          content=$(cat hi.txt)
          echo "Содержимое файла hi.txt: $content"
